[2018-12-27T13:11:13,022][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Setting "" hasn't been registered>, :backtrace=>["/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:32:in `get_setting'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:64:in `set_value'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:83:in `merge'", "org/jruby/RubyHash.java:1342:in `each'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:83:in `merge'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:135:in `validate_all'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/runner.rb:244:in `execute'", "/tmp/package/logstash-5.5.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/runner.rb:209:in `run'", "/tmp/package/logstash-5.5.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/tmp/package/logstash-5.5.0/lib/bootstrap/environment.rb:71:in `(root)'"]}
[2018-12-27T13:12:35,408][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Setting "" hasn't been registered>, :backtrace=>["/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:32:in `get_setting'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:64:in `set_value'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:83:in `merge'", "org/jruby/RubyHash.java:1342:in `each'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:83:in `merge'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:135:in `validate_all'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/runner.rb:244:in `execute'", "/tmp/package/logstash-5.5.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/runner.rb:209:in `run'", "/tmp/package/logstash-5.5.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/tmp/package/logstash-5.5.0/lib/bootstrap/environment.rb:71:in `(root)'"]}
[2018-12-27T13:12:56,106][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Setting "" hasn't been registered>, :backtrace=>["/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:32:in `get_setting'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:64:in `set_value'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:83:in `merge'", "org/jruby/RubyHash.java:1342:in `each'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:83:in `merge'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:135:in `validate_all'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/runner.rb:244:in `execute'", "/tmp/package/logstash-5.5.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/runner.rb:209:in `run'", "/tmp/package/logstash-5.5.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/tmp/package/logstash-5.5.0/lib/bootstrap/environment.rb:71:in `(root)'"]}
[2018-12-27T13:15:46,866][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Setting "" hasn't been registered>, :backtrace=>["/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:32:in `get_setting'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:64:in `set_value'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:83:in `merge'", "org/jruby/RubyHash.java:1342:in `each'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:83:in `merge'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:135:in `validate_all'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/runner.rb:244:in `execute'", "/tmp/package/logstash-5.5.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/runner.rb:209:in `run'", "/tmp/package/logstash-5.5.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/tmp/package/logstash-5.5.0/lib/bootstrap/environment.rb:71:in `(root)'"]}
[2018-12-27T13:23:44,432][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Setting "" hasn't been registered>, :backtrace=>["/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:32:in `get_setting'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:64:in `set_value'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:83:in `merge'", "org/jruby/RubyHash.java:1342:in `each'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:83:in `merge'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/settings.rb:135:in `validate_all'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/runner.rb:244:in `execute'", "/tmp/package/logstash-5.5.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/tmp/package/logstash-5.5.0/logstash-core/lib/logstash/runner.rb:209:in `run'", "/tmp/package/logstash-5.5.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/tmp/package/logstash-5.5.0/lib/bootstrap/environment.rb:71:in `(root)'"]}
